version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      VITE_MAP_DATA_API: https://overpass-api.de/api/interpreter
      FAST_REFRESH: false
      SKIP_PREFLIGHT_CHECK: true
      VITE_API_URL: https://rally.fly.dev